AWSTemplateFormatVersion: '2010-09-09'
Description: Full Infrastructure for Cloud Resume Challenge (S3, CloudFront, Route53)

Parameters:
  DomainName:
    Type: String
    Default: ma-resume.com
    Description: The custom domain name (e.g. ma-resume.com)
  CertificateArn:
    Type: String
    Description: The ARN of the manually created SSL Certificate in ACM

Resources:
  # 1. S3 BUCKET (Storage)
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-v3" # Creating a fresh v3 bucket to avoid conflicts
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  # 2. BUCKET POLICY (Permissions)
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${ResumeBucket}/*'

  # 3. CLOUDFRONT DISTRIBUTION (CDN & SSL)
  ResumeDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !Select [2, !Split ["/", !GetAtt ResumeBucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only # S3 Website endpoints are HTTP
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  # 4. ROUTE 53 RECORD (DNS)
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # This is the fixed Zone ID for CloudFront
        DNSName: !GetAtt ResumeDistribution.DomainName