AWSTemplateFormatVersion: '2010-09-09'
Description: Full Infrastructure for Cloud Resume Challenge (S3, CloudFront, Route53)

Parameters:
  DomainName:
    Type: String
    Default: ma-resume.com
    Description: The custom domain name (e.g. ma-resume.com)
  CertificateArn:
    Type: String
    Description: The ARN of the manually created SSL Certificate in ACM

Resources:
  # 1. S3 BUCKET (Storage)
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-v3" # Creating a fresh v3 bucket to avoid conflicts
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  # 2. BUCKET POLICY (Permissions)
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${ResumeBucket}/*'

  # 3. CLOUDFRONT DISTRIBUTION (CDN & SSL)
  ResumeDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !Select [2, !Split ["/", !GetAtt ResumeBucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only # S3 Website endpoints are HTTP
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  # 4. ROUTE 53 RECORD (DNS)
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # This is the fixed Zone ID for CloudFront
        DNSName: !GetAtt ResumeDistribution.DomainName

  # 5. DYNAMODB TABLE (Visitor Counter)
  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: crc-visitor-counter
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST     

  # 6. IAM ROLE FOR LAMBDA
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: LambdaDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt VisitorCounterTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  # 7. LAMBDA FUNCTION
  VisitorCounterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crc-visitor-counter-func
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table('crc-visitor-counter')
          def lambda_handler(event, context):
              response = table.get_item(Key={'id': 'visitors'})
              count = response.get('Item', {}).get('count', 0)
              new_count = int(count) + 1
              table.put_item(Item={'id': 'visitors', 'count': new_count})
              return {
                  'statusCode': 200,
                  'headers': {
                      'Access-Control-Allow-Origin': '*',
                      'Access-Control-Allow-Methods': 'GET,POST,OPTIONS'
                  },
                  'body': json.dumps({'count': str(new_count)})
              }    
  # 8. API GATEWAY
  VisitorCounterAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: crc-visitor-counter-api

  VisitorCounterResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VisitorCounterAPI
      ParentId: !GetAtt VisitorCounterAPI.RootResourceId
      PathPart: "get"

  VisitorCounterMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VisitorCounterAPI
      ResourceId: !Ref VisitorCounterResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt VisitorCounterFunction.Arn

  VisitorCounterDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: VisitorCounterMethod
    Properties:
      RestApiId: !Ref VisitorCounterAPI
      StageName: prod

  # 9. PERMISSION FOR API TO CALL LAMBDA
  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VisitorCounterFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VisitorCounterAPI}/*/GET/get"            